---
output:
  md_document:
    variant: markdown_github
---
# Reproducible Research Course Project 1

## Reading in the data

```{r, echo = TRUE}
setwd("G:/Coursera/Data Science/5-Reproducible Research")
dt <- read.csv("activity.csv", colClasses = c("numeric", "character","numeric"))
dt$date <- as.Date(dt$date,"%Y-%m-%d")
head(dt)
```


## Calculating the total number of steps
```{r}
total <- aggregate(dt$steps , by= list(dt$date), FUN = sum)
colnames(total) <- c("date","steps")
head(total)
```

## Calculating the mean and the median of the data
```{r}
mstep <- mean(total$steps, na.rm = TRUE)
mstep
median <- median(total$steps, na.rm = TRUE)
median
```

##Plotting the histogram
```{r}
hist(total$steps, col = "blue", xlab = "Steps", main = "Total number of steps per day")
```

##Time series
```{r}
tseries <- tapply(dt$steps, dt$interval, mean, na.rm = TRUE)
plot(row.names(tseries), tseries,type = "l", col = "blue", xlab = "Time Interval" , ylab = "Average Steps")
minterval <- which.max(tseries)
names(minterval)
```

## Taking care of missing values

Replacing the missing values using the mean.

```{r}
missing <-sum(is.na(dt$steps))
missing
newdt <- dt

replaceNA <- aggregate(steps ~ interval , data = newdt, FUN = mean)
for( i in 1:nrow(newdt)) {
  if(is.na(newdt[i,1])) {
    int <- newdt[i,3]
    newdt[i,1] <- replaceNA[replaceNA$interval == int, "steps"]
  }
}
head(replaceNA)
```
##Calculating new median and mean

```{r}
ntotal <- aggregate(newdt$steps , by= list(newdt$date), FUN = sum)
colnames(ntotal) <- c("date","steps")
nmstep <- mean(ntotal$steps)
nmedian <- median(ntotal$steps)
```

##Comparing new and old data sets
```{r}
par(mfrow = c(2,1))
hist(ntotal$steps, col = "red" , xlab = "Steps", main = "Total number of steps per days")
hist(total$steps, col = "blue", xlab = "Steps", main = "Total number of steps per day")
```

##Comparing weekdays and weekends

```{r}
bdata <- dt
bdata$steps[is.na(bdata$steps)] <- median(dt$steps, na.rm = TRUE)
bdata <- aggregate(steps ~ date + interval, data = bdata, sum, na.rm = TRUE)

bdata$date <- as.Date(bdata$date)    
bdata$day <- weekdays(bdata$date)
bdata$weekend <- as.factor(ifelse(bdata$day == "Saturday" | bdata$day == "Sunday", "weekend", "weekday"))

library(lattice)
plotdata <- aggregate(steps ~ interval + weekend, bdata, mean)
xyplot(steps ~ interval | factor(weekend), data=plotdata, aspect=2/3, type="l" ,layout = c(1,2))
```
